xGov-197 - CompX -  xUSD -> COMPX Staking
algorandfoundation/xGov pull request #197
Opened 2024-04-24 10:09 UTC by xxiled-plastic-cat

Initial proposal commit

2024-05-05 15:42 UTC, SudoWeezy requested changes

2024-05-05 15:42 UTC, SudoWeezy commented on Proposals/xgov-197.md
> +
Please add the subpart with relevant information about the deliverable here.

```suggestion
### Deliverable
Proposals must include clear, non-technical descriptions of deliverables.
```

2024-05-08 07:50 UTC, SudoWeezy approved these changes

2024-05-08 07:52 UTC, merged

2024-08-06 12:57 UTC, xxiled-plastic-cat commented
Work and deliverables complete: https://github.com/compx-labs/staking-contracts

Staking pools available at https://app.compx.io/staking-pools